### ISSUE TITLE
sharing book

### ISSUE THREAD

**Issue by gunzpro21** [Phambaonam/refactoring-improving-the-design-of-existing-code#1]
Chào bạn, mình thấy quyển sách này rất hay ban có thể  cho mình file PDF đc k?

**Comment by Phambaonam** [comment]
Hi bạn, do vấn đề bản quyền lên mình không thể public cuốn sách lên github được, nhưng mình có cách giúp bạn đọc cuốn sách này. Bạn vào trang oreilly.com theo [link này](https://www.oreilly.com/library/view/refactoring-improving-the/9780134757681/) để tạo tài khoản, bạn được dùng free 10 ngày để đọc tất cả các sách có trên oreilly.com, trong đó có cuốn Refactoring: Improving the Design of Existing Code version 2. Nếu sau 10 ngày bạn chưa đọc xong được thì có thể tạo tài khoản mới để đọc tiếp.
